analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.1541353
  brandStrength: 1
  lightness: 0.5558539
  brandColors:
    - '#F3E7D8'
    - '#040303'
    - '#9CA1A4'
    - '#274066'
    - '#FCBD53'
  rhythmicContrast: 0.387218
typography_spectrum: 0.9307196
layout_spectrum: 0.556928
cta:
  bucket: null
  version: null
  domain: null
favicon: null
name: CapturedSociety
