cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.320623
  brandStrength: 1
  lightness: 0.8233083
  brandColors:
    - '#D8D6CF'
    - '#CF4B3A'
    - '#4A3A30'
    - '#99896F'
    - '#FFE15C'
  rhythmicContrast: 0.7277121
typography_spectrum: 0.9307196
layout_spectrum: 0.556928
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: CapturedSociety
